---
- name: Install Zabbix6.0 to Ubuntu18.04 using ansible
  hosts: target
  remote_user: root
  become: yes
  gather_facts: false
  vars:
    local_path: /root/playbook/zabbix6.0
    remote_path: /root/
  tasks:
    - name: Update the System Packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install expect
      apt:
        name: expect
        state: latest

    - name: Install Mariadb package
      apt:
        name:
          - apt-transport-https
          - curl
        state: present

    - name: Install Mariadb package2
      shell: |
        curl -o /etc/apt/trusted.gpg.d/mariadb_release_signing_key.asc 'https://mariadb.org/mariadb_release_signing_key.asc'
        sh -c "echo 'deb https://tw1.mirror.blendbyte.net/mariadb/repo/10.5/ubuntu bionic main' >>/etc/apt/sources.list"
        rm -rf /var/lib/apt/lists/lock*
      register: install1

    - name: Install zabbix package
      shell: |
        wget https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4%2Bubuntu18.04_all.deb
        dpkg -i zabbix-release_6.0-4+ubuntu18.04_all.deb
      register: install2

    - name: Again Update the System Packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install mariadb-server
      apt:
        name: mariadb-server
        state: latest

    - name: Start the Mariadb service
      service:
        name: mariadb
        state: started
        enabled: true
    - name: Query mariadb to zabbix
      shell: |
        mysql -e "create database zabbix character set utf8mb4 collate utf8mb4_bin;"
        mysql -e "create user zabbix@localhost identified by 'password';"
        mysql -e "grant all privileges on zabbix.* to zabbix@localhost;"
        zcat /usr/share/zabbix-sql-scripts/mysql/server.sql.gz | mysql --default-character-set=utf8mb4 -uzabbix -p"password" zabbix
      register: mariadb

    - name: Print mariadb
      debug: msg="{{mariadb.stdout_lines}}"

    - name: Install Apache2
      apt:
        name: apache2
        state: latest

    - name: Install Zabbix
      apt:
        pkg:
          - zabbix-server-mysql
          - zabbix-frontend-php
          - zabbix-apache-conf
          - zabbix-sql-scripts
          - zabbix-agent

    - name: Start the apache service
      service:
        name: apache2
        state: started
        enabled: true

    - name: Start the zabbix-server service
      service:
        name: zabbix-server
        state: started
        enabled: true

    - name: Start the zabbix-agent service
      service:
        name: zabbix-agent
        state: started
        enabled: true

    - name: Config DBPassword
      replace:
        path: /etc/zabbix/zabbix_server.conf
        regexp: "# DBPassword="
        replace: "DBPassword=password"

    - name: Start the Apache2
      service:
        name: apache2
        state: restarted

    - name: Start the zabbix-server service
      service:
        name: zabbix-server
        state: restarted

    - name: Start the zabbix-agent service
      service:
        name: zabbix-agent
        state: restarted