---
- name: Install Zabbix6.0 to Ubuntu20.04 using ansible
  hosts: target
  tasks:
    - name: Update the System Packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install zabbix package
      apt:
        deb: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4%2Bubuntu20.04_all.deb

    - name: Again Update the System Packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install mysql-8.0
      apt:
        pkg:
          - mysql-server-8.0
          - mysql-client-8.0
        state: latest
        update_cache: true

    - name: Install Apache2
      apt:
        name: apache2
        state: latest

    - name: Install Zabbix
      apt:
        pkg:
          - zabbix-server-mysql
          - zabbix-frontend-php
          - zabbix-apache-conf
          - zabbix-sql-scripts
          - zabbix-agent

    - name: Start the Mysql service
      service:
        name: mysql
        state: started
        enabled: true

    - name: Start the apache service
      service:
        name: apache2
        state: started
        enabled: true

    - name: Start the zabbix-server service
      service:
        name: zabbix-server
        state: started
        enabled: true

    - name: Start the zabbix-agent service
      service:
        name: zabbix-agent
        state: started
        enabled: true

    - name: Query mysql to zabbix
      shell: |
        mysql -e "create database zabbix character set utf8mb4 collate utf8mb4_bin;"
        mysql -e "create user zabbix@localhost identified by 'password';"
        mysql -e "grant all privileges on zabbix.* to zabbix@localhost;"
        mysql -e "set global log_bin_trust_function_creators = 1;"
      register: result1

    - name: Import initial schema
      shell: |
        zcat /usr/share/zabbix-sql-scripts/mysql/server.sql.gz | mysql --default-character-set=utf8mb4 -uzabbix -p"password" zabbix
      register: result2

    - name: Diable log options
      shell: |
        mysql -e "set global log_bin_trust_function_creators = 0;"
      register: result3

    - name: Config DBPassword
      replace:
        path: /etc/zabbix/zabbix_server.conf
        regexp: "# DBPassword="
        replace: "DBPassword=password"

    - name: Start the Apache2
      service:
        name: apache2
        state: restarted

    - name: Start the zabbix-server service
      service:
        name: zabbix-server
        state: restarted

    - name: Start the zabbix-agent service
      service:
        name: zabbix-agent
        state: restarted