---
- name: Stop Wellife Portal admin service
  hosts: pwcf-was
  gather_facts: false
  become: yes
  tasks:
    - name: Stop service
      vars:
        ansible_become_user: tomcat
        ansible_become_method: su
      command:
        cmd: |
          ./stop.sh
      args:
        chdir: /CLOUD/tomcat9/server/wellife-admin/bin

    - name: Check process
      shell: |
        ps -ef | grep tomcat | grep wellife-admin
      register: weladmin

    - name: Print result
      debug: 
        msg: 
          - "{{weladmin.stdout_lines}}"
