---
- name: Start Wellife Portal pums admin service
  hosts: pwcf-was
  gather_facts: false
  become: yes
  tasks:
    - name: Start service
      vars:
        ansible_become_user: tomcat
        ansible_become_method: su
      command:
        cmd: |
          ./start.sh
      args:
        chdir: /CLOUD/tomcat9/server/pums-admin/bin

    - name: Check process
      shell: |
        ps -ef | grep tomcat | grep pums-admin
      register: pums

    - name: Print result
      debug: 
        msg: 
          - "{{pums.stdout_lines}}"
