---
- name: Stop Wellife Portal pums user service
  hosts: pwcf-was
  gather_facts: false
  become: yes
  tasks:
    - name: Stop service
      vars:
        ansible_become_user: tomcat
        ansible_become_method: su
      command:
        cmd: |
          ./stop.sh
      args:
        chdir: /CLOUD/tomcat9/server/pums-user/bin

    - name: Check process
      shell: |
        ps -ef | grep tomcat | grep pums-user
      register: pums

    - name: Print result
      debug: 
        msg: 
          - "{{pums.stdout_lines}}"
