---
- name: Install Apache Tomcat10 using ansible
  hosts: target
  vars:
    local_path: /root/playbook/tomcat8.5
    remote_path: /usr/local
  tasks:
    - name: Remove lock file
      shell: |
        rm -rf /var/lib/dpkg/lock*
      register: lockfile

    - name: Print lockfile
      debug: msg="{{lockfile.stdout_lines}}"

    - name: Update the System Packages
      yum:
        name: "*"
        state: latest
        update_cache: yes

    - name: Stop firewalld service
      service:
        name: firewalld
        state: stopped
        enabled: false

    - name: Install JAVA
      yum:
        name: java-1.8.0-openjdk-devel.x86_64
        state: latest

    - name: JAVA PATH
      lineinfile:
        path: /etc/profile
        state: present
        line: "{{ item }}"
      with_items:
      - "JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.362.b08-1.el7_9.x86_64"
      - "CATALINA_HOME=/usr/local/tomcat8"
      - "CLASSPATH=$JAVA_HOME/jre/lib:$JAVA_HOME/lib/tools.jar:$CATALINA_HOME/lib-jsp-api.jar:$CATALINA_HOME/lib/servlet-api.jar"
      - "PATH=$PATH:$JAVA_HOME/bin:/bin:/sbin"
      - "export JAVA_HOME PATH CLASSPATH CATALINA_HOME"

    - name: Source JAVA PATH
      shell: source /etc/profile
      args:
        executable: /bin/bash

    - name: Copy tomcat8.5.tar.gz
      copy:
        src: "{{ local_path }}/apache-tomcat-8.5.87.tar.gz"
        dest: "{{ remote_path }}/apache-tomcat-8.5.87.tar.gz"

    - name: download & unarchive tomcat
      unarchive:
        src: apache-tomcat-8.5.87.tar.gz
        dest: "{{ remote_path }}"
#        remote_src: yes
#        extra_opts: [--strip-components=1]

    - name: Move tomcat Path
      shell: |
        mv /usr/local/apache-tomcat-8.5.87 /usr/local/tomcat8
      register: tomcat_path

    - name: Print tomcat_path
      debug: msg="{{tomcat_path.stdout_lines}}"

    - name: Copy Tomcat service from local to remote
      copy:
        src: /etc/centos/tomcat.service
        dest: /etc/systemd/system/
        mode: 0755

    - name: Start and Enable Tomcat8.5 on Server
      systemd:
        name: tomcat
        state: started
        daemon_reload: true