---
- name: Excute ajp protocol
  hosts: target
  gather_facts: false
  vars:
    LOCAL_PATH: "/root/playbook/tomcat/"
    REMOTE_PATH: "/usr/local/tomcat"
    NEW_HTTP_PORT: "8080"
    NEW_AJP_PORT: "9080"
    NEW_REDIRECT_PORT: "9443"
    TIME_OUT: "1000000"
  tasks:
    - name: Backup remote conf file
      command: 
        cmd: mv server.xml server.xml.bak
      args:
        chdir: /usr/local/tomcat/conf
        
    - name: Copy conf file to remote
      copy:
        src: "{{ LOCAL_PATH }}/conf/server.xml"
        dest: "{{ REMOTE_PATH }}/conf/server.xml"

    - name: Uncomment ajp protocol
      lineinfile:
        path: "{{ REMOTE_PATH }}/conf/server.xml"
        regexp: 'ANSIBLE AJP'
        state: absent

    - name: Configuration ajp protocal
      lineinfile:
        path: "{{ REMOTE_PATH }}/conf/server.xml"
        regexp: 'AJP_PORT'
        line: '               port="{{ NEW_AJP_PORT }}"'

    - name: Configuration redirectPort
      lineinfile:
        path: "{{ REMOTE_PATH }}/conf/server.xml"
        regexp: 'REDIRECT_PORT'
        line: '               redirectPort="{{ NEW_REDIRECT_PORT }}" />'

    - name: Configuration redirectPort
      lineinfile:
        path: "{{ REMOTE_PATH }}/conf/server.xml"
        regexp: 'REDIRECT_PORT'
        line: '               redirectPort="{{ NEW_REDIRECT_PORT }}" />'

    - name: Configuration http protocol
      lineinfile:
        path: "{{ REMOTE_PATH }}/conf/server.xml"
        regexp: 'HTTP_PORT'
        line: '    <Connector port="{{ NEW_HTTP_PORT }}"'

    - name: Configuration connectionTimeout
      lineinfile:
        path: "{{ REMOTE_PATH }}/conf/server.xml"
        regexp: 'TIME_OUT'
        line: '               connectionTimeout="{{ TIME_OUT }}"'

    - name: config catalina.sh
      lineinfile:
        path: "{{ REMOTE_PATH }}/bin/catalina.sh"
        line: "{{ item }}"
      with_items:
        - ' CATALINA_OPTS="-server -Xms2048M -Xmx2048M'
        - '-XX:PermSize=128M '
        - '-XX:MaxPermSize=128M '
        - '-Xnoclassgc -XX:NewSize=512M'
        - '-XX:MaxNewSize=1024M'
        - '-XX:+UseParNewGC'
        - '-XX:ParallelGCThreads=4'
        - '-XX:+UseConcMarkSweepGC'
        - '-XX:CMSInitiatingOccupancyFraction=50'
        - '-XX:+PrintGCDetails'
        - '-XX:+PrintGCTimeStamps'
        - '-XX:+PrintHeapAtGC'
        - '-XX:+AggressiveOpts'
        - '-Djava.net.preferIPv4Stack=true'
        - '-Djava.awt.headless=true"'

    - name: Server Restart Tomcat
      service:
        name: tomcat
        state: restarted
