---
- name: Stop RPA service
  gather_facts: false
  become: yes
  tasks:
    - name: Stop first service
      command:
        cmd: |
          ./tomcat-stop.sh
          ./stop.sh
          ./activemq-stop.sh
      args:
        chdir: /data/rpa/bin

    - name: Stop second service
      expect:
        command:
          cmd: ./mysql-stop.sh
        args:
          chdir: /data/rpa/bin
        responses: 
          Enter password: "rpago!23"

    - name: Check rpa status
      command:
        cmd: |
          ./ps-rpa.sh
      args:
        chdir: /data/rpa/bin

    - name: Check process status
      shell: |
        ps -ef | grep tomcat
        ps -ef | grep activemq
        ps -ef | grep mariadb
      register: process

    - name: Print result
      debug: 
        msg: 
          - "{{process.stdout_lines}}"
