---
- name: Apache httpd Start service
  hosts: poma-push
  vars:
    ansible_become_user: apache
    ansible_become_method: su
    ansible_pass: "tltjfeks1!"
  gather_facts: false
  tasks:
    - name: Start service
      command: 
        cmd: |
          ./apache_start.sh
      args:
        chdir: /home/apache

    - name: Check process
      shell: |
        ps -ef | grep httpd | grep -v grep
      resgister: httpd

    - name: Print result
      debug: 
        msg: 
          - "{{httpd.stdout_lines}}"
