---
- name: Start Apache httpd service
  hosts: pwcf-web
  vars:
    ansible_become_user: apache
    ansible_become_method: su
    ansible_pass: "tltjfeks1!"
  tasks:
    - name: Start service
      command:
        cmd: |
          ./apache_start.sh
      args:
        chdir: /home/apache

    - name: Check process
      shell: |
        ps -ef | grep httpd | grep -v grep
      register: httpd

    - name: Print result
      debug: 
        msg: 
          - "{{httpd.stdout_lines}}"
