---
- hosts: target
  name: Script start
  become: yes
  become_method: sudo
  gather_facts: false
  vars:
    local_path: /root/inspect
    remote_path: /cloit
    date: "{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
    home: "{{ lookup('env', 'HOME') }}"
  tasks:
    - name: Directory create
      file:
        path: "{{ remote_path }}"
        state: directory

    - name: Log file create
      file:
        path: "{{ remote_path }}/{{ date }}_result.txt"
        state: touch

    - name: Script Send
      copy:
        src: "{{ local_path }}/integ_inspect.sh"
        dest: "{{ remote_path }}/integ_inspect.sh"
        owner: root
        group: root
        mode: '0755'

    - name: Script Run
      shell: |
        sh "{{ remote_path }}/integ_inspect.sh" >> "{{ remote_path }}/{{ date }}_result.txt"
      register: result

    - name: Copy Result.log From Remote to Local
      fetch:
        src: /cloit/{{ date }}_result.txt
        dest: /root/target 

    - name: Script remove
      file:
        path: "{{ remote_path }}"
        state: absent

    - name: Log remove
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ home }}/chrony_check.txt"
        - "{{ home }}/ntp_act1.txt"
        - "{{ home }}/disk_act1.txt"
        - "{{ home }}/disk_act2.txt"
        - "{{ home }}/disk_act3.txt"

    - name: Remove ansible syslog
      shell: |
        sed -i '/ansible/d' /var/log/messages
      register: ansible

    - name: Print ansible
      debug: msg="{{ansible.stdout_lines}}"
