---
- name: NHN backup agent stop
  hosts: pom
  gather_facts: false
  become: yes
  tasks:
    - name: Stop NHN agent
      shell: |
        tcbackup stop
      register: result

    - name: Print result
      debug: msg="{{result.stdout_lines}}"

    - name: Check process status
      shell: |
        ps -ef | grep avamar
      register: process

    - name: Print process status
      debug: 
        msg: 
          - "{{process.stdout_lines}}"
