---
- name: OZ Report8.0 tomcat start
  gather_facts: false
  hosts: poma-in-was
  become: yes
  tasks:
    - name: Start tomcat
      vars:
        ansible_become_user: tomcat
        ansible_become_method: su
      command:
        cmd: |
          ./stop.sh
      args:
        chdir: /CLOUD/tomcat9/server/ap_oz80/bin

    - name: Check process status
      shell: |
        ps -ef | grep tomcat | grep ao_oz80
      register: oz

    - name: Print result
      debug: 
        msg: 
          - "{{oz.stdout_lines}}"
