---
- name: HAproxy tomcat stop
  gather_facts: false
  hosts: poma-in-was
  become: yes
  tasks:
    - name: Stop tomcat
      vars:
        ansible_become_user: tomcat
        ansible_become_method: su
      command:
        cmd: |
          ./stop_haproxy.sh
      args:
        chdir: /CLOUD//linkSW/haproxy/bin

    - name: Check process status
      shell: |
        ps -ef | grep haproxy | grep -v grep
      register: ha

    - name: Print result
      debug: 
        msg: 
          - "{{ha.stdout_lines}}"
