---
- name: HAproxy tomcat start
  gather_facts: false
  hosts: poma-in-was
  become: yes
  tasks:
    - name: Start tomcat
      vars:
        ansible_become_user: tomcat
        ansible_become_method: su
      command:
        cmd: |
          ./start_haproxy.sh
      args:
        chdir: /CLOUD/linkSW/haproxy/bin

    - name: Check process status
      shell: |
        ps -ef | grep haproxy | grep -v grep
      register: ha

    - name: Print result
      debug: 
        msg: 
          - "{{ha.stdout_lines}}"
