---
- name: StreamDocs8.0 tomcat start
  gather_facts: false
  hosts: poma-in-was
  become: yes
  tasks:
    - name: Start tomcat
      vars:
        ansible_become_user: tomcat
        ansible_become_method: su
      command:
        cmd: |
          ./start.sh
      args:
        chdir: /CLOUD/tomcat9/server/ap_streamdocs/bin

    - name: Check process status
      shell: |
        ps -ef | grep tomcat | grep ap_streamdocs
      register: stdoc

    - name: Print result
      debug: 
        msg: 
          - "{{stdoc.stdout_lines}}"
