---
- name: Year-End system tomcat stop
  gather_facts: false
  hosts: poma-in-was
  become: yes
  tasks:
    - name: Stop tomcat
      vars:
        ansible_become_user: tomcat
        ansible_become_method: su
      command:
        cmd: |
          ./stop.sh
      args:
        chdir: /CLOUD/tomcat9/server/poma_ytsis_in/bin

    - name: Check process status
      shell: |
        ps -ef | grep tomcat | grep ytsis_in
      register: ytsis

    - name: Print result      
      debug: 
        msg: 
          - "{{ytsis.stdout_lines}}"
